---
title: "CodeBook"
author: "Ana Laura Tapia"
date: "7 de junio de 2017"
output: html_document
---

Las variables usadas en la base de datos provienen del acelerómetro y
giroscopio de los celulares en 3 ejes, las señales se usaron para generar
variables para los vectores X,Y y Z.

Algunas de las variables usadas son:
-tBodyAcc-XYZ
-tGravityAcc-XYZ
-tBodyAccJerk-XYZ
-tBodyGyro-XYZ
-tBodyGyroJerk-XYZ
-tBodyAccMag...

Algunas de las señales derivadas de estas variables son:
mean(): Media
std(): Desviación estandar
mad(): Desviación media absoluta 
max(): Valor más grande de los datos
min(): Valor más pequño de los datos
sma(): Signal magnitude area...

El experimento se realizó con un grupo de 30 persona entre los 19 y 48 años.
Cada persona hizo 6 actividades usando un Samsung Galaxy o la cadera. Usando el
acelerómetro y giroscopio del celular se obtuvieron datos de distintas variables

Ordenamos la base de datos usando nombres de actividad, agregando etiquetas apropiadas con nombres
de las variables que las describan.

Se muestra el promedio de cada variable para cada actividad y cada sujeto. 

FRAGMENTO DE TABLA:

ID Subject                 Activity      tBodyAcc-mean-X  tBodyAcc-mean-Y   tBodyAcc-mean-Z tBodyAcc-std-X 
1            1            1 WALKING         0.2773308      -0.017383819       -0.11114810     -0.283740259     
2            1       2 WALKING_UPSTAIRS     0.2554617      -0.023953149       -0.09730200     -0.354708025     
3            1       3 WALKING_DOWNSTAIRS   0.2891883      -0.009918505       -0.10756619      0.030035338     
4            1            4 SITTING         0.2612376      -0.001308288       -0.10454418     -0.977229008     
5            1           5 STANDING         0.2789176      -0.016137590       -0.11060182     -0.995759902     
6            1             6 LAYING         0.2215982      -0.040513953       -0.11320355     -0.928056469    
7            2            1 WALKING         0.2764266      -0.018594920       -0.10550036     -0.423642838     
8            2        2 WALKING_UPSTAIRS    0.2471648      -0.021412113       -0.15251390     -0.304376406      
9            2       3 WALKING_DOWNSTAIRS   0.2776153      -0.022661416       -0.11681294      0.046366681      
10           2            4 SITTING         0.2770874      -0.015687994       -0.10921827     -0.986822280     
11           2           5 STANDING         0.2779115      -0.018420827       -0.10590854     -0.987271889     
12           2             6 LAYING         0.2813734      -0.018158740       -0.10724561     -0.974059465     
13           3            1 WALKING         0.2755675      -0.017176784       -0.11267486     -0.360356726     
14           3        2 WALKING_UPSTAIRS    0.2608199      -0.032410941       -0.11006486     -0.313123438
........
